#!/system/bin/sh
# TEE Simulator Plus — Installation Script

SKIPUNZIP=0

# ===== Environment Detection =====
TSP_ENV=""
if [ -n "$KSU" ] || [ -d "/data/adb/ksu/" ]; then
    TSP_ENV="kernelsu"
    ui_print "- Environment: KernelSU detected"
elif [ -n "$MAGISK_VER_CODE" ]; then
    TSP_ENV="magisk"
    ui_print "- Environment: Magisk v${MAGISK_VER_CODE}"
else
    abort "! KernelSU or Magisk required"
fi

# ===== API Level =====
API=$(getprop ro.build.version.sdk)
[ -z "$API" ] && API=0
if [ "$API" -lt 29 ]; then
    abort "! Android 10+ (API 29+) required, found $API"
fi
ui_print "- Android API: $API"

# ===== Architecture =====
ARCH_REAL="${ARCH:-$(getprop ro.product.cpu.abi)}"
case "$ARCH_REAL" in
    arm64*|aarch64*) TSP_LIB="arm64-v8a" ;;
    arm*|armeabi*)   TSP_LIB="armeabi-v7a" ;;
    *) abort "! Unsupported arch: $ARCH_REAL" ;;
esac
ui_print "- Architecture: $ARCH_REAL"

ui_print "- Module files extracted to $MODPATH"

# ===== Tricky-Store directory setup =====
ui_print "- Setting up Tricky-Store directory: /data/adb/tricky_store/"
mkdir -p /data/adb/tricky_store 2>/dev/null
chmod 0755 /data/adb/tricky_store 2>/dev/null

# Preserve existing keybox.xml and target.txt
if [ -f /data/adb/tricky_store/keybox.xml ]; then
    ui_print "  - Existing keybox.xml preserved"
fi
if [ -f /data/adb/tricky_store/target.txt ]; then
    ui_print "  - Existing target.txt preserved"
else
    {
        echo "# Tricky-Store compatible target list"
        echo "# Generated by TEE Simulator Plus"
    } > /data/adb/tricky_store/target.txt
    chmod 0644 /data/adb/tricky_store/target.txt
fi

# ===== Native library placement =====
if [ -f "$MODPATH/libs/$TSP_LIB/libteesimplus.so" ]; then
    mkdir -p "$MODPATH/system/lib64" "$MODPATH/system/lib" 2>/dev/null
    if [ "$TSP_LIB" = "arm64-v8a" ]; then
        cp "$MODPATH/libs/$TSP_LIB/libteesimplus.so" "$MODPATH/system/lib64/" 2>/dev/null
    else
        cp "$MODPATH/libs/$TSP_LIB/libteesimplus.so" "$MODPATH/system/lib/" 2>/dev/null
    fi
    ui_print "  - Native library installed for $TSP_LIB"
else
    ui_print "  ! Native library not found (build may have failed)"
fi

# ===== Permissions =====
ui_print "- Setting permissions..."
set_perm_recursive "$MODPATH/scripts" 0 0 0755 0755
set_perm_recursive "$MODPATH/webroot" 0 0 0755 0644
set_perm_recursive "$MODPATH/config" 0 0 0755 0644
set_perm_recursive "$MODPATH/logs" 0 0 0755 0644
[ -f "$MODPATH/post-fs-data.sh" ] && set_perm "$MODPATH/post-fs-data.sh" 0 0 0755
[ -f "$MODPATH/service.sh" ] && set_perm "$MODPATH/service.sh" 0 0 0755

ui_print ""
ui_print "============================================"
ui_print "  TEE Simulator Plus — Installed"
ui_print "============================================"
ui_print "  Env:    $TSP_ENV"
ui_print "  API:    $API"
ui_print "  Arch:   $TSP_LIB"
ui_print "  Keybox: /data/adb/tricky_store/keybox.xml"
ui_print "  Target: /data/adb/tricky_store/target.txt"
ui_print "============================================"
ui_print "- Reboot to activate"
