#!/system/bin/sh
# TEE Simulator Plus — post-fs-data
# Runs early in boot before Zygote starts.

MODDIR="${0%/*}"
TRICKY_STORE_DIR="/data/adb/tricky_store"
LOGFILE="$MODDIR/logs/module.log"

mkdir -p "$MODDIR/logs" 2>/dev/null

# Skip if disabled
[ -f "$MODDIR/disable" ] && exit 0

_log() {
    echo "$(date '+%Y-%m-%d %H:%M:%S') [INFO] post-fs-data: $1" >> "$LOGFILE" 2>/dev/null
}

_log "starting"

# Ensure tricky_store directory exists
mkdir -p "$TRICKY_STORE_DIR"
chmod 0755 "$TRICKY_STORE_DIR"

# Initialize empty target.txt if missing
if [ ! -f "$TRICKY_STORE_DIR/target.txt" ]; then
    {
        echo "# Tricky-Store compatible target list"
        echo "# Generated by TEE Simulator Plus"
    } > "$TRICKY_STORE_DIR/target.txt"
    chmod 0644 "$TRICKY_STORE_DIR/target.txt"
fi

# Status logging
if [ -f "$TRICKY_STORE_DIR/keybox.xml" ]; then
    _log "keybox.xml present at $TRICKY_STORE_DIR/keybox.xml"
else
    _log "no keybox.xml configured (use WebUI to upload)"
fi

_target_count=$(grep -v '^[[:space:]]*#' "$TRICKY_STORE_DIR/target.txt" 2>/dev/null | grep -v '^[[:space:]]*$' | wc -l | tr -d ' ')
_log "target list count: $_target_count"

_log "completed"
