#!/system/bin/sh
# TEE Simulator Plus — Target list manager (Tricky-Store compatible)
# Target file: /data/adb/tricky_store/target.txt

MODDIR="${MODDIR:-/data/adb/modules/tee-simulator-plus}"
TRICKY_STORE_DIR="${TRICKY_STORE_DIR:-/data/adb/tricky_store}"
TARGET_FILE="$TRICKY_STORE_DIR/target.txt"

mkdir -p "$TRICKY_STORE_DIR" 2>/dev/null
[ -f "$TARGET_FILE" ] || {
    {
        echo "# Tricky-Store compatible target list"
        echo "# Generated by TEE Simulator Plus"
    } > "$TARGET_FILE"
    chmod 0644 "$TARGET_FILE"
}

_json_get_str() {
    echo "$1" | sed -n "s/.*\"$2\"[[:space:]]*:[[:space:]]*\"\([^\"]*\)\".*/\1/p" | head -1
}

_escape_json() {
    printf '%s' "$1" | sed 's/\\/\\\\/g; s/"/\\"/g'
}

_read_targets() {
    [ -f "$TARGET_FILE" ] || { echo ""; return; }
    grep -v '^[[:space:]]*#' "$TARGET_FILE" 2>/dev/null | grep -v '^[[:space:]]*$' | sed 's/[[:space:]]//g'
}

_write_targets() {
    {
        echo "# Tricky-Store compatible target list"
        echo "# Generated by TEE Simulator Plus"
        echo ""
        if [ -n "$1" ]; then
            echo "$1"
        fi
    } > "$TARGET_FILE"
    chmod 0644 "$TARGET_FILE"
}

_validate_pkg() {
    echo "$1" | grep -qiE '^[a-z][a-z0-9_]*(\.[a-z0-9][a-z0-9_]*)+$'
}

cmd_target_list_installed() {
    _targets=$(_read_targets)

    # pm list packages -3 returns lines like "package:com.foo.bar"
    _pm_out=$(pm list packages -3 2>/dev/null)
    if [ -z "$_pm_out" ]; then
        # Fallback: also include system apps when third-party query fails
        _pm_out=$(pm list packages 2>/dev/null)
    fi

    if [ -z "$_pm_out" ]; then
        echo '{"status":0,"data":[]}'
        return 0
    fi

    # Build JSON array
    _result=""
    _first=1
    _IFS_BAK="$IFS"
    IFS='
'
    for _line in $_pm_out; do
        _pkg=$(echo "$_line" | sed 's/^package://; s/[[:space:]]//g')
        [ -z "$_pkg" ] && continue

        # Check if in target list
        _is_target=false
        if echo "$_targets" | grep -qx "$_pkg"; then
            _is_target=true
        fi

        # App name = use package name as label (dumpsys is too slow for full list)
        _app_name="$_pkg"
        _pkg_e=$(_escape_json "$_pkg")
        _name_e=$(_escape_json "$_app_name")

        _entry="{\"packageName\":\"$_pkg_e\",\"appName\":\"$_name_e\",\"isTarget\":$_is_target}"
        if [ $_first -eq 1 ]; then
            _result="$_entry"
            _first=0
        else
            _result="$_result,$_entry"
        fi
    done
    IFS="$_IFS_BAK"

    echo "{\"status\":0,\"data\":[$_result]}"
}

cmd_target_add() {
    _pkg=$(_json_get_str "$1" "packageName")
    [ -z "$_pkg" ] && { echo '{"status":1,"message":"packageName required"}'; return 1; }

    if ! _validate_pkg "$_pkg"; then
        echo "{\"status\":2,\"message\":\"Invalid package name format\"}"
        return 2
    fi

    _targets=$(_read_targets)
    if echo "$_targets" | grep -qx "$_pkg"; then
        # Already in list, no-op
        _count=$(echo "$_targets" | grep -v '^$' | wc -l | tr -d ' ')
        echo "{\"status\":0,\"data\":{\"packageName\":\"$_pkg\",\"count\":$_count,\"alreadyExists\":true}}"
        return 0
    fi

    if [ -n "$_targets" ]; then
        _new="${_targets}
${_pkg}"
    else
        _new="$_pkg"
    fi

    _write_targets "$_new"
    _count=$(echo "$_new" | grep -v '^$' | wc -l | tr -d ' ')
    echo "{\"status\":0,\"data\":{\"packageName\":\"$_pkg\",\"count\":$_count}}"
}

cmd_target_remove() {
    _pkg=$(_json_get_str "$1" "packageName")
    [ -z "$_pkg" ] && { echo '{"status":1,"message":"packageName required"}'; return 1; }

    _targets=$(_read_targets)
    _new=$(echo "$_targets" | grep -vx "$_pkg")
    _write_targets "$_new"
    _count=$(echo "$_new" | grep -v '^$' | wc -l | tr -d ' ')
    echo "{\"status\":0,\"data\":{\"packageName\":\"$_pkg\",\"count\":$_count}}"
}

cmd_target_import() {
    _path=$(_json_get_str "$1" "path")
    [ -z "$_path" ] && { echo '{"status":1,"message":"path required"}'; return 1; }
    [ ! -f "$_path" ] && { echo '{"status":2,"message":"File not found"}'; return 2; }

    _existing=$(_read_targets)
    _imported=0
    _duplicates=0
    _new="$_existing"

    while IFS= read -r _line || [ -n "$_line" ]; do
        _line=$(echo "$_line" | sed 's/^[[:space:]]*//; s/[[:space:]]*$//')
        [ -z "$_line" ] && continue
        case "$_line" in \#*) continue ;; esac
        if ! _validate_pkg "$_line"; then continue; fi

        if echo "$_new" | grep -qx "$_line"; then
            _duplicates=$((_duplicates + 1))
            continue
        fi
        if [ -n "$_new" ]; then
            _new="${_new}
${_line}"
        else
            _new="$_line"
        fi
        _imported=$((_imported + 1))
    done < "$_path"

    _write_targets "$_new"
    _total=$(echo "$_new" | grep -v '^$' | wc -l | tr -d ' ')
    echo "{\"status\":0,\"data\":{\"imported\":$_imported,\"duplicates\":$_duplicates,\"total\":$_total}}"
}

cmd_target_export() {
    # File is already at TARGET_FILE
    _count=$(_read_targets | grep -v '^$' | wc -l | tr -d ' ')
    _path_e=$(_escape_json "$TARGET_FILE")
    echo "{\"status\":0,\"data\":{\"path\":\"$_path_e\",\"count\":$_count}}"
}

# Dispatcher
_input="$1"
_command=$(_json_get_str "$_input" "command")

case "$_command" in
    target_list_installed) cmd_target_list_installed ;;
    target_add)            cmd_target_add "$_input" ;;
    target_remove)         cmd_target_remove "$_input" ;;
    target_import)         cmd_target_import "$_input" ;;
    target_export)         cmd_target_export ;;
    *) echo "{\"status\":1,\"message\":\"Unknown: $_command\"}" ;;
esac
